# Generated by Django 4.2.11 on 2025-06-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitnessClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField()),
                ("instructor", models.CharField(max_length=100)),
                ("total_slots", models.IntegerField()),
                ("available_slots", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_email", models.EmailField(max_length=254)),
                ("booking_time", models.DateTimeField(auto_now_add=True)),
                (
                    "fitness_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.fitnessclass",
                    ),
                ),
            ],
        ),
    ]
